emilkowalski/sonner

package.json

Add some fields for sidebar information on https://www.npmjs.com/package/sonner.

chore: add npm fields

---

README.md

docs: readme typo

---

src/index.tsx

This PR fixes the toast keep following mouse pointer when the mouse button is released.
https://github.com/emilkowalski/sonner/assets/48808846/1d31f459-c0b9-4fc5-85e9-24fc7645dbd8
https://github.com/emilkowalski/sonner/assets/48808846/22574764-51dd-4806-9f07-729456658311

Fix toast keep follow pointer on pointer up

---

src/state.ts
src/types.ts
website/src/components/Types/Types.tsx

Add types to infer the promise data type in `success` function

Infer the promise data type in toast promise

---

src/index.tsx

Well... in my previous [PR](https://github.com/emilkowalski/sonner/pull/72) the swipe up stopped working. This PR fix it :sweat_smile:

Fix swipe to top

---

src/assets.tsx

Default case does not do anything currently

fix: return null as default asset

---

README.md

Adds solid-sonner to list of ports

docs: add solid port link

---

src/index.tsx
src/styles.css
test/src/app/page.tsx
test/tests/basic.spec.ts

This PR make a few things:
- Focus the last focused element when the list is unmounted
- Return focus back to last focused element when tabbing forward out of list
- Show close button when toast is focused 
https://github.com/emilkowalski/sonner/assets/48808846/988b1b82-d2a7-42f2-883f-e269e6f96ed6
https://github.com/emilkowalski/sonner/assets/48808846/75594489-6bf4-4041-bdda-0992eaecd6ee

Improve keyboard navigation

---

test/src/app/page.tsx
test/tests/basic.spec.ts

Add swipe up and theme tests

---

website/app/globals.css

Stumbled upon this while searching for `Toaster` styles 😃

fix(website): Correct CSS comment format

---

src/index.tsx
src/types.ts
website/app/page.tsx
website/src/components/Position/index.tsx

feat: allow setting position when creating a toast

---

src/state.ts

Fixes #160
- Takes into account that `data` can be undefined, which results in an error right now
- Shows each toast only if the corresponding state is set
- Dismisses a loading toast on `finally` if none of `success` or `error` are set. This prevents a loading toast from being visible indefinitely.

Make `PromiseData` partial in `toast.promise`

---

src/state.ts
website/src/components/Hero/index.tsx
website/src/pages/toast.mdx

Custom toasts were not added to the toasts array before.

Close custom toasts

---

src/index.tsx

Removed an unnecessary console.log from the index.tsx file

Remove unnecessary console.log

---

website/src/components/Hero/index.tsx

Remove unstyled prop from Hero toast

---

website/src/components/Types/Types.tsx

Current displayed code is different from what's executed

fix incorrect demo code for promise toasts

---

package.json
pnpm-lock.yaml

There're few bug fixes and a small perf improvement in the past few patches

build: bump bundler for perf purpose

---

src/state.ts
src/types.ts

feat: `description` support function in promise

---

.github/issue-template.md
.github/pull-request-template.md

Closes https://github.com/emilkowalski/sonner/issues/285

add PR and issue templates

---

src/index.tsx
src/types.ts
website/src/pages/styling.mdx
website/src/pages/toaster.mdx

Temporary revert as it's breaking types and styles.

Fix types of toaster icons

---

src/index.tsx
src/types.ts

Add close button prop to toast

---

package.json
pnpm-lock.yaml
tsup.config.ts
website/src/components/Hero/index.tsx

Bunchee was causing some issues with styles.

Swap bundlers

---

src/index.tsx

Allow to style all unstyled toasts with the default prop

---

src/index.tsx
src/types.ts
website/src/pages/styling.mdx
website/src/pages/toaster.mdx

Allow users to customize icons from toaster

---

src/index.tsx

Closes https://github.com/emilkowalski/sonner/issues/176
https://github.com/emilkowalski/sonner/assets/68275535/6e792083-b280-409d-a13e-5740225286a3

Add hooks to show active toasts

---

src/index.tsx

Replace icons in a promise correctly

---

src/index.tsx

Display loading icon for loading toast

---

website/src/pages/toast.mdx

Opening this PR following this issue: https://github.com/emilkowalski/sonner/issues/341
- Add explanation and example for rendering a toast on initial page load

[Docs]: Render toast on page load

---

src/index.tsx

[Closes https://github.com/emilkowalski/sonner/issues/](https://github.com/emilkowalski/sonner/issues/364)
- [ Update ClassName for custom loading icon]
- [Update incorrect custom icon rendering]
N/A

fix: unmount custom loading icon correctly

---

package.json
pnpm-lock.yaml
src/styles.css

Decrease specificity

---

src/index.tsx
src/styles.css
src/types.ts

Closes #414 
allows individual toasts to opt into richColor styling
N/A

feat(#414): allow individual toasts to opt into richColor styling

---

package.json
pnpm-lock.yaml
src/index.tsx

Remove dom purify to reduce bundle size

---

website/src/pages/toaster.mdx

fix(toaster): fix typo

---

src/state.ts

fix toast timer

---

src/index.tsx

Fix dependency array

---

src/assets.tsx
src/index.tsx
src/types.ts
test/src/app/page.tsx

Closes #454
Add support for custom close icons
N/A

feat: add support for custom close icon

---

src/styles.css
website/src/components/Position/index.tsx

Closes #412
Closes #320 
To keep consistent styling I tried matching the same hover behavior from light mode.
https://github.com/user-attachments/assets/538bfe4c-897c-45ed-8d87-7de1bbef516b

fix: dark mode for close button

---

src/index.tsx

https://github.com/emilkowalski/sonner/issues/524

fix: next build error

---

src/index.tsx
src/styles.css
src/types.ts
website/src/pages/toaster.mdx

resolve https://github.com/emilkowalski/sonner/issues/396

feat: add options to configure offsets on mobile

---

src/index.tsx
src/state.ts

Fix bad `setState()` call, expose new toast util called `getToasts()`.

fix: useSonner hook

---

src/styles.css

If you need your toasts to be unstyled you probably should go headless. 
https://sonner.emilkowal.ski/styling#headless

refactor: remove unstyled prop

---

src/index.tsx
src/styles.css
test/tests/basic.spec.ts

`data-theme` is often used in many apps already.

chore: rename data-theme to data-sonner-theme

---

src/index.tsx
src/styles.css

No more accidental expanded state change, no reset on subsequential swipes.

chore: horizontal swiping improvements

---

src/index.tsx
src/styles.css

While it looks better with lift, it was causing some hover state bugs.

chore: remove lift interaction

---

pnpm-lock.yaml
src/index.tsx
website/src/components/Hero/index.tsx

Right click caused infinite drag.

fix: right click event swallowing
