- src/styles.css
Check if toast is mounted to apply styles when expanded. I think this will fix #2, the issue seems to be the same.
https://user-images.githubusercontent.com/48808846/221070315-96b27f37-77a2-410d-b257-11f2caa5d818.mp4
https://user-images.githubusercontent.com/48808846/221070412-de57b673-3691-42d4-9771-3a9a59647771.mp4
> Fix height while are expanded

- src/styles.css
Avoid setting hover to false when swiping out to top and sometimes I saw a flash when swipe out the toast so I added `forwards` to `swipe-out` animation.
https://user-images.githubusercontent.com/48808846/221189672-3cff19b6-8cfd-4abf-bd3e-366054fd2576.mp4
https://user-images.githubusercontent.com/48808846/221189731-5302f5ec-3f0e-4142-9565-86533950f1af.mp4
> fix avoid set hover to false when swiping out to top

- website/src/components/Types/Types.tsx
[<img align=right width="50%" alt="the current Types section" src="https://user-images.githubusercontent.com/886627/221256743-d818db21-14ec-422c-9abc-f85de60e3717.png">][site] The current **Types** section [on the website][site] seems to have the wrong copy… 😬 (It looks like it was copy-and-pasted from the **Rich Colors** section accidentally and never got updated!)
[site]: https://sonner.emilkowal.ski
[rdme]: https://github.com/emilkowalski/sonner#types
> docs(website): match types copy to readme.md

- src/styles.css
As noticed at [Issue #11](https://github.com/emilkowalski/sonner/issues/11) `@keyframes` may be overwriten. I added a simple prefix just to differ keyframes from sonner.
> add a prefix to prevent overwriting keyframes

- README.md
- src/index.tsx
- src/types.ts
Thanks for your work on this package, I love it!
This PR adds the ability to specify classNames to use for the description. You can either set the descriptionClassName on the `<Toaster/>` component or on individual toasts.
This is super handy for Tailwind users. For example:
```tsx
toast('The thing was successful', {
description: 'Here\'s some additional info about the thing',
className: 'font-medium text-gray-800',
descriptionClassName: 'font-normal text-gray-500'
});
```
or
```tsx
<Toaster toastOptions={{descriptionClassName: 'font-normal text-gray-500'}} />
```
> Add ability to add className to description

- src/index.tsx
- src/state.ts
- src/types.ts
- test/src/app/page.tsx
- test/tests/basic.spec.ts
As said in #82, this PR:
- updates toast properties itself in promise API instead of using local variables
- Not remove toast when event prevented in `action`
Fixes #82
> Toast promise title

- src/state.ts
- src/types.ts
- test/src/app/page.tsx
- test/tests/basic.spec.ts
Closes #117 
Adds the `finally` property to `toast.promise`. This property expects a function that will be called whenever the promise resolves or rejects — unlike the other properties, it does not have an effect on the rendered toast.
> add finally to toast.promise

- src/styles.css
Removed a math operation since it's simpler to use * 1.05
> Simplify math for calculating +5%

- package.json
- tsup.config.ts
* use relative path for ts type
* remove the esbuild `banner` as "use client" is already handled. now the `dist/index.js` only has one "use client" directive on top
> remove duplicated use client directive

- src/styles.css
Before:
After
(Thanks for this amazing toaster package!)
> Fix potential title and description overflowing

- src/state.ts
- test/src/app/page.tsx
- test/tests/basic.spec.ts
Fixes this issue: https://github.com/emilkowalski/sonner/issues/155
I went for the quick fix by setting `toasterCounter ` to start at 1 rather than 0.
If this is undesired, and you'd rather fix it by correcting the faulty comparisons, then that's understandable.
I added a test which should help you debug, regardless.
> Bugfix: Update now works for first toastId

- src/assets.tsx
- src/index.tsx
- src/state.ts
**Title:** enhance type imports
**Description of Changes:**
- Added the `type` keyword in your imports from `./types.ts`
**Benefits:**
import type only imports declarations to be used for type annotations and declarations.
**Request for Review:**
Please review and provide your feedback on these changes.
> type: import types with keyword

- src/index.tsx
Added an empty arrow function as an event handler for the close button. This provides a clearer indication that the case where the event should do nothing has been considered. Additionally, it improves the readability of the code and makes the logic more explicit.
> Added empty arrow function to close button

- src/state.ts
This function looks forgotten. Added the ability to get the id immediately after calling the function, as for all other toast functions
> Returning the id for a custom toast

- src/index.tsx
- src/types.ts
- test/src/app/page.tsx
- test/tests/basic.spec.ts
First approach to add custom styles to action and cancel button. I have also added a test to check that everything is correct.
Waiting for any suggestions.
> Styles for action and cancel buttons

- src/state.ts
- website/src/components/Types/Types.tsx
The fetch API does not reject a promise on HTTP error status such as 404 or 500. Instead, it resolves the promise with the ok property set to false. So we add an additional check for the .ok property.
> Account for fetch in promise

- src/index.tsx
- src/types.ts
This PR adds the `containerAriaLabel` and `closeButtonAriaLabel` props to allow for accessible internationalisation.
> Props for toast container and close button aria-labels

- src/index.tsx
Add check on document, otherwise document is not defined in fresh
> Fresh deno compatibility

- src/styles.css
Small styling change that makes the close button visible by default when closeButton prop is passed. Thus making the component more accessible.
---
Closed this originally, as I thought this had introduced a bug, but seems to be the nuance of the global Toaster component not really handling toggling the close functionality on/off dynamically. E.g. you click the close example, and then access toasts from there, they will also have the close button. 
I did think you could just `setCloseButton` to false on dismiss / autoclose, but that would have other side effects - like when viewing multiple toasts with close on.
> Resolves: #224 - Close button is always visible on toast when defined

- src/state.ts
- src/types.ts
#242 issue fix 
---
Updated the types and the state by adding a property ```default``` to the ```classNames``` property
> feat: add default property to classNames to the toast function and Toaster component

- src/index.tsx
After the changes in [this PR](https://github.com/emilkowalski/sonner/pull/206), the`closeTimerRemainingTimeRef` ref is no longer used. This PR removes it.
> refactor: remove unused remaining time ref

- src/index.tsx
- src/types.ts
Just started using sonner and realized `action.label` & `cancel.label` could accept `ReactNode` instead of `string` so you can pass in a more complex custom label including an icon or whatever.
Hope you agree, if not I'd be curious of possible downsides I might not've considered and can be closed.
Closes: #273
Also just saw that `cancel.onClick` is typed `onClick?: () => void;` while `action.onclick` = `onClick: (event: React.MouseEvent<HTMLButtonElement>) => void;` is there a reason or should I open another PR to add the event to `cancel.onClick` as well?
> types: change label types to ReactNode

- src/index.tsx
- src/types.ts
- website/src/pages/toast.mdx
- website/src/pages/toaster.mdx
`closeButton` option in `toast(...)` did not take precdence over the `Toaster` global setting if passing `false`. 
You could test this like so:
```tsx
<Toaster closeButton />
// ...
toast("Foo", { closeButton: false })
```
the toast should NOT have the close button rendered. And can test the inverse too.
> fix: make closeButton option in toast take precedence over Toaster

- src/styles.css
Closes https://github.com/emilkowalski/sonner/issues/258
- Moved ghost-div in before-meta tag one level behind to make sure it doesn't block the clickable area
N/A
> ghost-div doesn't block click in Firefox

- src/index.tsx
- src/types.ts
Toast position breaks when firing toasts in different positions
Closes https://github.com/emilkowalski/sonner/issues/311
- `positions` prop added to `HeightT` interface
- new `positions` prop is used to filter toasts and heights when calculating the offset of the element `<li>`
You can fire toasts in different position without messing with the offset.
> Avoid issues with `<li>` offest when using different positions

- src/hooks.tsx
- src/index.tsx
- src/types.ts
- website/src/pages/toaster.mdx
Closes https://github.com/emilkowalski/sonner/issues/303
- Create `useIsDocumentHidden` hook
- Add `pauseWhenDocumentHidden` prop to `Toast` and `Toaster`
- Add logic to pause `Toast` timers when document is hidden
- Document prop for `Toaster`
N/A
> Implement option to pause when document is hidden

- src/index.tsx
- src/types.ts
- website/src/pages/toaster.mdx
Support a custom cn function, for example if you want to use `clsx` or [`tailwind-merge` ](https://github.com/dcastil/tailwind-merge). In particular I was looking for the tw-merge use case
> feature: custom cn function

- src/index.tsx
- src/types.ts
Two elements, `data-icon` and `data-content`, would benefit from having distinct classNames for more precise control, avoiding the need for a custom toast implementation or reliance on complex nested CSS selectors.
> feat: add classNames for content/icon elements

- src/styles.css
Closes #370
Calculate the mobile width based on `--mobile-offset` instead of a hardcoded value to make it always centered. 
**Before**
**After**
> fix: dynamic mobile width based on `--mobile-offset`

- src/index.tsx
Closes #340 
`setTimeout(, Infinity)` behaves as if the delay is 0.
As a result, the toast would be closed immediately, giving the appearance that it was never rendered.
To solve this, we skip setting the timer for closing the toast.
N/A
> fix: toast not displaying when `Toaster.duration` is set to Infinity

- src/index.tsx
Closes #374 
Use the `gap` prop instead of the fixed `GAP` constant.
> fix: `Toaster.gap` doesn't work

- src/index.tsx
v1.4.41 released my changes for supporting additonal classNames for icon and content. When using a `toast.error`, `toast.success`, `toast.warning`, etc. the classNames defined for icon and content are not being applied. This will resolve that.
> fix: apply classnames when using toast[type]

- src/index.tsx
- test/src/app/page.tsx
- test/tests/basic.spec.ts
Closes https://github.com/emilkowalski/sonner/issues/378
Before:
After:
> fix: rendering of `ReactNode` descriptions

- src/index.tsx
For Sonner to be bundled in other libraries, we need to export `ToasterProps`.
This fixes following error for library authors:
```
TS4023: Exported variable 'X' has or is using name 'ToasterProps' from external module './node_modules/sonner/dist/index' but cannot be named
```
Closes https://github.com/emilkowalski/sonner/issues/399
- exported `ToasterProps` from index
> export ToasterProps type

- src/index.tsx
- src/types.ts
Closes https://github.com/emilkowalski/sonner/issues/397
N/A
> feat: updates toast action/cancel property type/handlers

- pnpm-lock.yaml
- src/index.tsx
Closes https://github.com/emilkowalski/sonner/issues/176
I have implemented this on https://github.com/emilkowalski/sonner/pull/347 but it failed the test. This time, I fix the removeToast function to make it pass the test 
https://github.com/emilkowalski/sonner/assets/68275535/50208bdd-eaa0-4d38-891f-c3738268d956
> Add hooks to show active toasts

- src/hooks.tsx
The flag `pauseWhenPageIsHidden` works fine when you are on the page -> toast appears -> you switch to another tab = timers paused. But when the tab with your app is in the background and you render your toasts(e.g. through WebSockets) timers don't pause.
> Pause timer if toast appears when the document is hidden

- website/src/pages/toast.mdx
It seems the section about "persistent toast" in this [PR](https://github.com/emilkowalski/sonner/pull/46/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) didn't make it to the new docs. 
Closes https://github.com/emilkowalski/sonner/issues/429 
- Update the `toast.mdx` to include a few lines about how to make a toast persist forever
> chore(docs): include a section about persisting toasts

- src/state.ts
- src/types.ts
Async functions in `toast.promise` will lead to toasts with the message: `[object Promise]`
---
@emilkowalski Any reason why `toast.promise` doesn't return a promise that resolves when its input promise resolves? Any chance I can implement #339 ?
> Handle async functions in `toast.promise` results

- src/state.ts
This PR fixes a bug when you can't dismiss a toast with id = 0
> Allow dismissing toasts with id = 0

- package.json
Closes https://github.com/emilkowalski/sonner/issues/456
According to [Node.js documentation](https://nodejs.org/api/packages.html#package-entry-points) only on older versions of Node.js should `main` be required.
> For new packages targeting the currently supported versions of Node.js, the ["exports"](https://nodejs.org/api/packages.html#exports) field is recommended. For packages supporting Node.js 10 and below, the ["main"](https://nodejs.org/api/packages.html#main) field is required. If both ["exports"](https://nodejs.org/api/packages.html#exports) and ["main"](https://nodejs.org/api/packages.html#main) are defined, the ["exports"](https://nodejs.org/api/packages.html#exports) field takes precedence over ["main"](https://nodejs.org/api/packages.html#main) in supported versions of …
> fix: add "main" entry to package.json

- src/styles.css
Closes https://github.com/emilkowalski/sonner/issues/452
> fix: reverse left position on mobile `rtl`

- website/src/pages/toast.mdx
The API reference docs for `toast()` is incorrect. This PR fixes it.
> update API reference for toast()

- package.json
Similarly to how it's done in `radix-ui/primitives`, we can allow React.js v19 in peerDependencies, as this library should pretty much be compatible with v19.
https://github.com/radix-ui/primitives/blob/74b182b401c8ca0fa5b66a5a9a47f507bb3d5adc/packages/react/collection/package.json#L39-L40
N/A
> fix: allow React.js v19 in peerDependencies

- src/index.tsx
N/A
Added `forwardRef` to `Toaster` component to allow access for wrappers that need to manipulate the inner node.
N/A
> feat: allow ref forwarding for `Toaster`

- pnpm-lock.yaml
- src/state.ts
- test/next.config.js
- test/package.json
- test/src/app/action.tsx
- test/src/app/page.tsx
- tsconfig.json
- website/src/components/CodeBlock/code-block.module.css
- website/src/components/Hero/hero.module.css
- website/src/globals.css
- website/src/style.css
Closes Nothing
Support show response from RSC if it's a JSX element
https://github.com/user-attachments/assets/c4295e34-30b9-4a90-b101-ad8a2693333a
> feat: support show react element from react server function

- package.json
Related-to https://github.com/emilkowalski/sonner/issues/386
Granted, this should be seen as a workaround, since the css is already bundled in the js. The root cause of Remix's spotty support for sonner is unclear, but referencing the css directly works for me:
```typescript
import sonnerStyles from 'sonner/dist/styles.css?url'
export const links: LinksFunction = () => [
{ rel: 'stylesheet', href: sonnerStyles },
]
```
N/A
> Include styles.css in dist

- src/assets.tsx
- src/index.tsx
Closes https://github.com/emilkowalski/sonner/issues/488
- add className passthrough to the default Loader component
- pass the configured loader classes to each possible loader element
N/A
> fix: implement loader class from config

- src/index.tsx
fix https://github.com/emilkowalski/sonner/issues/391
`useEffect` and `useLayoutEffect` both listen to toast.id and include the same logic, so remove the repeated calls to cancel the duplicate toast array
> fix: remove repeat effect hook to resolve mix up

- src/index.tsx
Closes https://github.com/emilkowalski/sonner/issues/172#issuecomment-2261611845
This PR restores the ability to prevent a toast from closing when action button is clicked by using `event.preventDefault()` in the `onClick` callback.
The current behavior does not honor `onClick`'s `event.preventDefault()`, which was unintentionally broken by https://github.com/emilkowalski/sonner/commit/7d28d42b368fd65f02d1d903c673111f3a430701.
The intended behavior is stated in the [documentation](https://sonner.emilkowal.ski/toast#action):
> You can prevent the toast from closing by calling `event.preventDefault()` in the `onClick` callback.
N/A
> Fix inability to prevent toast from closing on action button click

- src/index.tsx
- src/state.ts
- src/types.ts
- website/src/components/Hero/index.tsx
- website/src/pages/toast.mdx
You can render custom elements inside the toast like `<a />` or custom components by passing a function instead of a string. This work for both the title and description.
```jsx
toast(
() => (
<>
View{' '}
<a href="https://google.com" target="_blank">
Animation on the Web
</a>
</>
),
{
description: () => <button>This is a button element!</button>,
},
);
```
> feat: allow to pass custom elements to title and description

- src/index.tsx
Closes https://github.com/emilkowalski/sonner/issues/512
- Change `swipeAmount` to check if `y` is `top` which makes top-positioned toasts only able to be swiped upward (negative values) and bottom-positioned toasts only able to be swiped downward (positive values).
> Fix top position swipe direction

- package.json
In some cases, using `import 'sonner/dist/styles.css'` to import may cause Vite build errors.
see: https://github.com/vitejs/vite/discussions/2657
Reproduce the demo:
[https://github.com/molvqingtai/wxt-import-css-report](https://github.com/molvqingtai/wxt-import-css-report)
> fix: styles.css is not declared in package.json

- src/index.tsx
Adds a ref to `<section` in Toaster.
See https://github.com/emilkowalski/sonner/issues/535
> Utilize ref in Toaster

- src/index.tsx
- test/src/app/page.tsx
- test/tests/basic.spec.ts
Inability to update toast duration dynamically
closed #529
> fix: inability to update toast duration dynamically #529

- src/index.tsx
For cases where `<Toaster />` is accidentally added to `<html>` instead of `<body>`
> fix: hydration warning

- .github/workflows/playwright.yml
- src/index.tsx
The mouseUp event can be swallowed by e.g. a link in the toast and then the toast will follow the mouse around and never go away as it still think its being dragged.
> fix: swallowed mouseUp event

- src/state.ts
- src/types.ts
Resolves #464
Introduce new types and extend existing functionality to allow for more detailed toast messages in promise handling. This enhancement improves the flexibility of toast notifications by incorporating additional properties.
Usage:
```
toast.promise<{ name: string }>(
() =>
new Promise((resolve, reject) => {
setTimeout(() => {
resolve({ name: 'Sonner' });
}, 2000);
}),
{
loading: 'Loading...',
success: (data) => {
return {
message: `${data.name} toast has been added`,
description: 'Custom description for the Success state',
};
},
error: {
message: 'An error occurred',
description: undefined, // overrides default description set below
action: {
label: 'Retry',
onClick: () => {
console.log('retrying');
},
},
},
description: 'Global description',
},
)
```
This is a non-breaking …
> Enhance Promise to support ExternalToast propertiesfeat: Promise enhancement to allow ExternalToast props

- src/index.tsx
If the toast is closed while `toastType` is `loading`, the user will not be able to see the completed result.
Therefore, it seems that `toastType` is prevented from closing when it is `loading`.
However, since there are two issues related to this, to avoid any misunderstanding, it might be better not to render the close button when the `toastType` is `loading`.
Therefore, I am submitting a pull request to ensure that the close button is not rendered when `toastType` is `loading`.
#514 #476
> chore: Hide the close button when toastType is loading

- src/state.ts
Passing a ReactNode as a message will render an empty toast since typeof promiseData === 'object' is true (a ReactNode is an object).
Fix: check if type promiseData === 'object' and not a valid React Element.
> fix: isExtendedResult. Check if promiseData is an object and not a valid React Element

- src/styles.css
> feat: inherit color for description when rich colors is `true`

- .github/workflows/playwright.yml
- package.json
Current `package.json` specifies `pnpm@8.12.1` but `pnpm-lock.yaml` has `lockfileVersion: '9.0'`. This version mismatch causes unintended lockfile changes when developers run `pnpm install` after cloning the repository.
- pnpm v8 automatically converts lockfileVersion to `6.0`
- lockfileVersion `9.0` was adopted in pnpm v9.0.0+
reference: [pnpm v9.0.0 release](https://github.com/pnpm/pnpm/releases/tag/v9.0.0)
- Upgraded `packageManager` from `pnpm@8.12.1` to `pnpm@9.15.9`
- Chose `9.15.9` as a latest release in the v9 series
Unintended changes in `pnpm-lock.yaml` after running `pnpm install` on a git clone.
> chore: upgrade pnpm to v9 to fix lockfileVersion mismatch

- src/index.tsx
- src/types.ts
- test/src/app/page.tsx
- test/tests/basic.spec.ts
Adds support for `testId` prop to individual toast components, enabling reliable e2e testing by allowing developers to target specific toasts with data-testid attributes.
- Added `testId?: string` prop to `ToastT` interface
- Renders `data-testid` attribute when `testId` is provided
- Added test coverage for the new functionality
```typescript
toast.success('Operation completed', { testId: 'success-toast' });
```
```typescript
await expect(page.getByTestId('success-toast')).toBeVisible();
```
Fixes the issue of being unable to reliably target specific toasts in e2e tests.
Fixes: #657
> feat: add testId prop for individual toast components

- src/index.tsx
- src/types.ts
- test/src/app/page.tsx
- test/tests/basic.spec.ts
- website/src/pages/toast.mdx
- website/src/pages/toaster.mdx
This PR adds support for rendering and targeting multiple Toaster components in the app. You can now:
- Render multiple `<Toaster />` instances, each with a unique `id` prop.
- Target toasts to a specific Toaster by passing a `toasterId` option to the `toast()` API.
- Closes #222
```jsx
<Toaster id="global" position="top-right" />
<Toaster id="canvas" position="bottom-left" />
<button onClick={() => toast('Global toast', { toasterId: 'global' })}>
Show in Global Toaster
</button>
<button onClick={() => toast('Canvas toast', { toasterId: 'canvas' })}>
Show in Canvas Toaster
</button>
```
- `<Toaster id="your-id" />` — Renders a Toaster instance with a unique id.
- `toast('Message', { toasterId: 'your-id' })` — Shows the toast only in the Toaster with the matching id.
- Toasts without a …
> feat(toaster): add support for multiple toasters with unique identifiers
